# Generated by Django 5.0.6 on 2024-05-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlay',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
